//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntitiProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CV_ENTITIEntities1 : DbContext
    {
        public CV_ENTITIEntities1()
            : base("name=CV_ENTITIEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_ADRES> TBL_ADRES { get; set; }
        public virtual DbSet<TBL_CALISMALARIM> TBL_CALISMALARIM { get; set; }
        public virtual DbSet<TBL_HAKKIMDA> TBL_HAKKIMDA { get; set; }
        public virtual DbSet<TBL_ILETISIM> TBL_ILETISIM { get; set; }
        public virtual DbSet<TBL_YETENEK> TBL_YETENEK { get; set; }
    }
}
